services:
  - type: web
    name: my-invidious-instance
    env: docker
    plan: free
    dockerfilePath: docker/Dockerfile
    envVars:
      - key: INVIDIOUS_DATABASE_URL
        fromDatabase:
          name: invidious-db
          property: connectionString

databases:
  - name: invidious-db
    plan: free
